micronaut:
  application.name: lillia

  security:
    authentication: bearer
    session.enabled: false
    reject-not-found: false
    token:
      refresh.cookie:
        enabled: true
        cookie-name: refresh-token
      cookie.cookie-name: access-token
      jwt:
        signatures:
          secret.generator.secret: ${JWT_SECRET_KEY:a-string-secret-at-least-256-bits-long}

        generator:
          refresh-token.secret: ${JWT_SECRET_KEY:a-string-secret-at-least-256-bits-long}
          access-token.expiration: 86400

    endpoints:
      login:
        path: /signin
        unsupported-post-content-type-status: 415
      logout:
        path: /signout
        unsupported-post-content-type-status: 415
      oauth:
        path: /renew
        unsupported-post-content-type-status: 415

    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

  serde:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    property-naming-strategy: SNAKE_CASE
    deserialization.ignore-unknown: true
    serialization:
      inclusion: ALWAYS
      always-serialize-errors-as-list: true

  data:
    pageable:
      default-page-size: 24
      max-page-size: 240
      sort-parameter-name: sort
      size-parameter-name: size
      page-parameter-name: page

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_URL:`postgresql://localhost:5432/lillia_dev`}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

r2dbc:
  datasources:
    default:
      db-type: postgres
      dialect: POSTGRES
      url: r2dbc:${DATABASE_URL:`postgresql://localhost:5432/lillia_dev`}
      username: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:postgres}
      options:
        protocol: postgres
        driver: pool

flyway.datasources.default.enabled: true
